// Define a simple function that takes an argument.
function fn(arg) {
  return `Hello, ${arg}.`;
}

// Define a set of arguments we can pass to the functon.
const args = ["Alice", "Bob", "Carol"];

// Display the set of results generated by the function.
for (const arg of args) {
  const result = fn(arg);
  console.log(result);
}
