// Display a set of (arg, result) pairs generated by a function.
const explorableFunction = {
  fn(arg) {
    return `Hello, ${arg}.`;
  },

  keys: ["Alice", "Bob", "Carol"],

  async *[Symbol.asyncIterator]() {
    yield* this.keys;
  },

  async get(key) {
    return this.fn(key);
  },
};

for await (const key of explorableFunction) {
  const value = await explorableFunction.get(key);
  console.log(value);
}
